/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookBookSlugRouteImport } from './routes/book.$bookSlug'
import { Route as ReadBookSlugSlugRouteImport } from './routes/read.$bookSlug.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookSlugRoute = BookBookSlugRouteImport.update({
  id: '/book/$bookSlug',
  path: '/book/$bookSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookSlugSlugRoute = ReadBookSlugSlugRouteImport.update({
  id: '/read/$bookSlug/$slug',
  path: '/read/$bookSlug/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book/$bookSlug': typeof BookBookSlugRoute
  '/read/$bookSlug/$slug': typeof ReadBookSlugSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book/$bookSlug': typeof BookBookSlugRoute
  '/read/$bookSlug/$slug': typeof ReadBookSlugSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book/$bookSlug': typeof BookBookSlugRoute
  '/read/$bookSlug/$slug': typeof ReadBookSlugSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book/$bookSlug' | '/read/$bookSlug/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book/$bookSlug' | '/read/$bookSlug/$slug'
  id: '__root__' | '/' | '/book/$bookSlug' | '/read/$bookSlug/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookBookSlugRoute: typeof BookBookSlugRoute
  ReadBookSlugSlugRoute: typeof ReadBookSlugSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookSlug': {
      id: '/book/$bookSlug'
      path: '/book/$bookSlug'
      fullPath: '/book/$bookSlug'
      preLoaderRoute: typeof BookBookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookSlug/$slug': {
      id: '/read/$bookSlug/$slug'
      path: '/read/$bookSlug/$slug'
      fullPath: '/read/$bookSlug/$slug'
      preLoaderRoute: typeof ReadBookSlugSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookBookSlugRoute: BookBookSlugRoute,
  ReadBookSlugSlugRoute: ReadBookSlugSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
