/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MangaRouteImport } from './routes/manga'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as BookBookSlugRouteImport } from './routes/book.$bookSlug'
import { Route as MangaIndexRouteImport } from './routes/manga.index'
import { Route as MangaSeriesSlugRouteImport } from './routes/manga.$seriesSlug'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioBookSlugRouteImport } from './routes/studio.$bookSlug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiChatImageIdRouteImport } from './routes/api/chat-image.$id'
import { Route as ApiBackupRouteImport } from './routes/api/backup'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'
import { Route as MangaSeriesSlugIndexRouteImport } from './routes/manga.$seriesSlug.index'
import { Route as MangaSeriesSlugChapterSlugRouteImport } from './routes/manga.$seriesSlug.$chapterSlug'
import { Route as ReadBookSlugSlugRouteImport } from './routes/read.$bookSlug.$slug'
import { Route as StudioBookSlugIndexRouteImport } from './routes/studio.$bookSlug.index'
import { Route as StudioBookSlugSlugRouteImport } from './routes/studio.$bookSlug.$slug'
import { Route as MangaSeriesSlugChapterSlugIndexRouteImport } from './routes/manga.$seriesSlug.$chapterSlug.index'
import { Route as MangaSeriesSlugChapterSlugEditRouteImport } from './routes/manga.$seriesSlug.$chapterSlug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaRoute = MangaRouteImport.update({
  id: '/manga',
  path: '/manga',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookSlugRoute = BookBookSlugRouteImport.update({
  id: '/book/$bookSlug',
  path: '/book/$bookSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIndexRoute = MangaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MangaRoute,
} as any)
const MangaSeriesSlugRoute = MangaSeriesSlugRouteImport.update({
  id: '/$seriesSlug',
  path: '/$seriesSlug',
  getParentRoute: () => MangaRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBookSlugRoute = StudioBookSlugRouteImport.update({
  id: '/$bookSlug',
  path: '/$bookSlug',
  getParentRoute: () => StudioRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatImageIdRoute = ApiChatImageIdRouteImport.update({
  id: '/api/chat-image/$id',
  path: '/api/chat-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupRoute = ApiBackupRouteImport.update({
  id: '/api/backup',
  path: '/api/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaSeriesSlugIndexRoute = MangaSeriesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MangaSeriesSlugRoute,
} as any)
const MangaSeriesSlugChapterSlugRoute =
  MangaSeriesSlugChapterSlugRouteImport.update({
    id: '/$chapterSlug',
    path: '/$chapterSlug',
    getParentRoute: () => MangaSeriesSlugRoute,
  } as any)
const ReadBookSlugSlugRoute = ReadBookSlugSlugRouteImport.update({
  id: '/read/$bookSlug/$slug',
  path: '/read/$bookSlug/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioBookSlugIndexRoute = StudioBookSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioBookSlugRoute,
} as any)
const StudioBookSlugSlugRoute = StudioBookSlugSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StudioBookSlugRoute,
} as any)
const MangaSeriesSlugChapterSlugIndexRoute =
  MangaSeriesSlugChapterSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MangaSeriesSlugChapterSlugRoute,
  } as any)
const MangaSeriesSlugChapterSlugEditRoute =
  MangaSeriesSlugChapterSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MangaSeriesSlugChapterSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/manga': typeof MangaRouteWithChildren
  '/media': typeof MediaRoute
  '/members': typeof MembersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRouteWithChildren
  '/book/$bookSlug': typeof BookBookSlugRoute
  '/manga/$seriesSlug': typeof MangaSeriesSlugRouteWithChildren
  '/studio/$bookSlug': typeof StudioBookSlugRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/manga/': typeof MangaIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/chat-image/$id': typeof ApiChatImageIdRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/manga/$seriesSlug/$chapterSlug': typeof MangaSeriesSlugChapterSlugRouteWithChildren
  '/read/$bookSlug/$slug': typeof ReadBookSlugSlugRoute
  '/studio/$bookSlug/$slug': typeof StudioBookSlugSlugRoute
  '/manga/$seriesSlug/': typeof MangaSeriesSlugIndexRoute
  '/studio/$bookSlug/': typeof StudioBookSlugIndexRoute
  '/manga/$seriesSlug/$chapterSlug/edit': typeof MangaSeriesSlugChapterSlugEditRoute
  '/manga/$seriesSlug/$chapterSlug/': typeof MangaSeriesSlugChapterSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/members': typeof MembersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/book/$bookSlug': typeof BookBookSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/manga': typeof MangaIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/chat-image/$id': typeof ApiChatImageIdRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/read/$bookSlug/$slug': typeof ReadBookSlugSlugRoute
  '/studio/$bookSlug/$slug': typeof StudioBookSlugSlugRoute
  '/manga/$seriesSlug': typeof MangaSeriesSlugIndexRoute
  '/studio/$bookSlug': typeof StudioBookSlugIndexRoute
  '/manga/$seriesSlug/$chapterSlug/edit': typeof MangaSeriesSlugChapterSlugEditRoute
  '/manga/$seriesSlug/$chapterSlug': typeof MangaSeriesSlugChapterSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/manga': typeof MangaRouteWithChildren
  '/media': typeof MediaRoute
  '/members': typeof MembersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRouteWithChildren
  '/book/$bookSlug': typeof BookBookSlugRoute
  '/manga/$seriesSlug': typeof MangaSeriesSlugRouteWithChildren
  '/studio/$bookSlug': typeof StudioBookSlugRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/manga/': typeof MangaIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/chat-image/$id': typeof ApiChatImageIdRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/manga/$seriesSlug/$chapterSlug': typeof MangaSeriesSlugChapterSlugRouteWithChildren
  '/read/$bookSlug/$slug': typeof ReadBookSlugSlugRoute
  '/studio/$bookSlug/$slug': typeof StudioBookSlugSlugRoute
  '/manga/$seriesSlug/': typeof MangaSeriesSlugIndexRoute
  '/studio/$bookSlug/': typeof StudioBookSlugIndexRoute
  '/manga/$seriesSlug/$chapterSlug/edit': typeof MangaSeriesSlugChapterSlugEditRoute
  '/manga/$seriesSlug/$chapterSlug/': typeof MangaSeriesSlugChapterSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/gallery'
    | '/login'
    | '/manga'
    | '/media'
    | '/members'
    | '/profile'
    | '/signup'
    | '/studio'
    | '/book/$bookSlug'
    | '/manga/$seriesSlug'
    | '/studio/$bookSlug'
    | '/u/$username'
    | '/manga/'
    | '/studio/'
    | '/api/chat-image/$id'
    | '/api/backup'
    | '/api/media/$id'
    | '/manga/$seriesSlug/$chapterSlug'
    | '/read/$bookSlug/$slug'
    | '/studio/$bookSlug/$slug'
    | '/manga/$seriesSlug/'
    | '/studio/$bookSlug/'
    | '/manga/$seriesSlug/$chapterSlug/edit'
    | '/manga/$seriesSlug/$chapterSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/gallery'
    | '/login'
    | '/media'
    | '/members'
    | '/profile'
    | '/signup'
    | '/book/$bookSlug'
    | '/u/$username'
    | '/manga'
    | '/studio'
    | '/api/chat-image/$id'
    | '/api/backup'
    | '/api/media/$id'
    | '/read/$bookSlug/$slug'
    | '/studio/$bookSlug/$slug'
    | '/manga/$seriesSlug'
    | '/studio/$bookSlug'
    | '/manga/$seriesSlug/$chapterSlug/edit'
    | '/manga/$seriesSlug/$chapterSlug'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/gallery'
    | '/login'
    | '/manga'
    | '/media'
    | '/members'
    | '/profile'
    | '/signup'
    | '/studio'
    | '/book/$bookSlug'
    | '/manga/$seriesSlug'
    | '/studio/$bookSlug'
    | '/u/$username'
    | '/manga/'
    | '/studio/'
    | '/api/chat-image/$id'
    | '/api/backup'
    | '/api/media/$id'
    | '/manga/$seriesSlug/$chapterSlug'
    | '/read/$bookSlug/$slug'
    | '/studio/$bookSlug/$slug'
    | '/manga/$seriesSlug/'
    | '/studio/$bookSlug/'
    | '/manga/$seriesSlug/$chapterSlug/edit'
    | '/manga/$seriesSlug/$chapterSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MangaRoute: typeof MangaRouteWithChildren
  MediaRoute: typeof MediaRoute
  MembersRoute: typeof MembersRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRouteWithChildren
  BookBookSlugRoute: typeof BookBookSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiChatImageIdRoute: typeof ApiChatImageIdRoute
  ApiBackupRoute: typeof ApiBackupRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ReadBookSlugSlugRoute: typeof ReadBookSlugSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga': {
      id: '/manga'
      path: '/manga'
      fullPath: '/manga'
      preLoaderRoute: typeof MangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookSlug': {
      id: '/book/$bookSlug'
      path: '/book/$bookSlug'
      fullPath: '/book/$bookSlug'
      preLoaderRoute: typeof BookBookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/': {
      id: '/manga/'
      path: '/'
      fullPath: '/manga/'
      preLoaderRoute: typeof MangaIndexRouteImport
      parentRoute: typeof MangaRoute
    }
    '/manga/$seriesSlug': {
      id: '/manga/$seriesSlug'
      path: '/$seriesSlug'
      fullPath: '/manga/$seriesSlug'
      preLoaderRoute: typeof MangaSeriesSlugRouteImport
      parentRoute: typeof MangaRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$bookSlug': {
      id: '/studio/$bookSlug'
      path: '/$bookSlug'
      fullPath: '/studio/$bookSlug'
      preLoaderRoute: typeof StudioBookSlugRouteImport
      parentRoute: typeof StudioRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-image/$id': {
      id: '/api/chat-image/$id'
      path: '/api/chat-image/$id'
      fullPath: '/api/chat-image/$id'
      preLoaderRoute: typeof ApiChatImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup': {
      id: '/api/backup'
      path: '/api/backup'
      fullPath: '/api/backup'
      preLoaderRoute: typeof ApiBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$seriesSlug/': {
      id: '/manga/$seriesSlug/'
      path: '/'
      fullPath: '/manga/$seriesSlug/'
      preLoaderRoute: typeof MangaSeriesSlugIndexRouteImport
      parentRoute: typeof MangaSeriesSlugRoute
    }
    '/manga/$seriesSlug/$chapterSlug': {
      id: '/manga/$seriesSlug/$chapterSlug'
      path: '/$chapterSlug'
      fullPath: '/manga/$seriesSlug/$chapterSlug'
      preLoaderRoute: typeof MangaSeriesSlugChapterSlugRouteImport
      parentRoute: typeof MangaSeriesSlugRoute
    }
    '/read/$bookSlug/$slug': {
      id: '/read/$bookSlug/$slug'
      path: '/read/$bookSlug/$slug'
      fullPath: '/read/$bookSlug/$slug'
      preLoaderRoute: typeof ReadBookSlugSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$bookSlug/': {
      id: '/studio/$bookSlug/'
      path: '/'
      fullPath: '/studio/$bookSlug/'
      preLoaderRoute: typeof StudioBookSlugIndexRouteImport
      parentRoute: typeof StudioBookSlugRoute
    }
    '/studio/$bookSlug/$slug': {
      id: '/studio/$bookSlug/$slug'
      path: '/$slug'
      fullPath: '/studio/$bookSlug/$slug'
      preLoaderRoute: typeof StudioBookSlugSlugRouteImport
      parentRoute: typeof StudioBookSlugRoute
    }
    '/manga/$seriesSlug/$chapterSlug/': {
      id: '/manga/$seriesSlug/$chapterSlug/'
      path: '/'
      fullPath: '/manga/$seriesSlug/$chapterSlug/'
      preLoaderRoute: typeof MangaSeriesSlugChapterSlugIndexRouteImport
      parentRoute: typeof MangaSeriesSlugChapterSlugRoute
    }
    '/manga/$seriesSlug/$chapterSlug/edit': {
      id: '/manga/$seriesSlug/$chapterSlug/edit'
      path: '/edit'
      fullPath: '/manga/$seriesSlug/$chapterSlug/edit'
      preLoaderRoute: typeof MangaSeriesSlugChapterSlugEditRouteImport
      parentRoute: typeof MangaSeriesSlugChapterSlugRoute
    }
  }
}

interface MangaSeriesSlugChapterSlugRouteChildren {
  MangaSeriesSlugChapterSlugEditRoute: typeof MangaSeriesSlugChapterSlugEditRoute
  MangaSeriesSlugChapterSlugIndexRoute: typeof MangaSeriesSlugChapterSlugIndexRoute
}

const MangaSeriesSlugChapterSlugRouteChildren: MangaSeriesSlugChapterSlugRouteChildren =
  {
    MangaSeriesSlugChapterSlugEditRoute: MangaSeriesSlugChapterSlugEditRoute,
    MangaSeriesSlugChapterSlugIndexRoute: MangaSeriesSlugChapterSlugIndexRoute,
  }

const MangaSeriesSlugChapterSlugRouteWithChildren =
  MangaSeriesSlugChapterSlugRoute._addFileChildren(
    MangaSeriesSlugChapterSlugRouteChildren,
  )

interface MangaSeriesSlugRouteChildren {
  MangaSeriesSlugChapterSlugRoute: typeof MangaSeriesSlugChapterSlugRouteWithChildren
  MangaSeriesSlugIndexRoute: typeof MangaSeriesSlugIndexRoute
}

const MangaSeriesSlugRouteChildren: MangaSeriesSlugRouteChildren = {
  MangaSeriesSlugChapterSlugRoute: MangaSeriesSlugChapterSlugRouteWithChildren,
  MangaSeriesSlugIndexRoute: MangaSeriesSlugIndexRoute,
}

const MangaSeriesSlugRouteWithChildren = MangaSeriesSlugRoute._addFileChildren(
  MangaSeriesSlugRouteChildren,
)

interface MangaRouteChildren {
  MangaSeriesSlugRoute: typeof MangaSeriesSlugRouteWithChildren
  MangaIndexRoute: typeof MangaIndexRoute
}

const MangaRouteChildren: MangaRouteChildren = {
  MangaSeriesSlugRoute: MangaSeriesSlugRouteWithChildren,
  MangaIndexRoute: MangaIndexRoute,
}

const MangaRouteWithChildren = MangaRoute._addFileChildren(MangaRouteChildren)

interface StudioBookSlugRouteChildren {
  StudioBookSlugSlugRoute: typeof StudioBookSlugSlugRoute
  StudioBookSlugIndexRoute: typeof StudioBookSlugIndexRoute
}

const StudioBookSlugRouteChildren: StudioBookSlugRouteChildren = {
  StudioBookSlugSlugRoute: StudioBookSlugSlugRoute,
  StudioBookSlugIndexRoute: StudioBookSlugIndexRoute,
}

const StudioBookSlugRouteWithChildren = StudioBookSlugRoute._addFileChildren(
  StudioBookSlugRouteChildren,
)

interface StudioRouteChildren {
  StudioBookSlugRoute: typeof StudioBookSlugRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioBookSlugRoute: StudioBookSlugRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MangaRoute: MangaRouteWithChildren,
  MediaRoute: MediaRoute,
  MembersRoute: MembersRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRouteWithChildren,
  BookBookSlugRoute: BookBookSlugRoute,
  UUsernameRoute: UUsernameRoute,
  ApiChatImageIdRoute: ApiChatImageIdRoute,
  ApiBackupRoute: ApiBackupRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ReadBookSlugSlugRoute: ReadBookSlugSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
